// 50 Daily Significance Mirror Affirmations
// These are randomly selected and displayed as a positive daily intention

export const dailyAffirmations: string[] = [
  "I matter because I make a difference through my presence.",
  "My kindness ripples further than I can see.",
  "I am seen, even when life feels quiet.",
  "The way I show up changes lives in small, sacred ways.",
  "I create connection simply by being me.",
  "I am worthy of deep, meaningful relationships.",
  "My contribution has value, even when it feels effortless.",
  "I am allowed to receive as much as I give.",
  "I belong in the lives of others.",
  "I build trust through my authenticity.",
  "My relationships grow stronger when I show my true self.",
  "I attract opportunities by being genuine and open-hearted.",
  "I am safe to be seen and known.",
  "I do not need to perform to be loved.",
  "My presence brings comfort to others.",
  "I make people feel valued without even trying.",
  "I am connected to life through meaningful moments.",
  "I am learning how to let myself be supported.",
  "I deserve closeness, warmth, and care.",
  "I am becoming more confident through connection.",
  "My relationships are a source of strength, not pressure.",
  "I am grateful for the people who walk beside me.",
  "I am gently expanding my capacity for intimacy and trust.",
  "I create safety in the way I listen.",
  "I am open to deeper conversations and real belonging.",
  "I bring light into rooms simply by being present.",
  "I allow myself to be known without fear.",
  "I grow through shared moments and honest connection.",
  "I give myself permission to feel close to others.",
  "I am supported even when I forget it.",
  "I am building relationships that nourish my soul.",
  "I am enough just as I am.",
  "My vulnerability strengthens my bonds, not weakens them.",
  "I trust that the right connections find me at the right time.",
  "I am becoming more confident in letting others see me.",
  "I bring warmth into every interaction.",
  "My life is richer because of the people in it.",
  "I am allowed to take up emotional space.",
  "I strengthen relationships through attention and care.",
  "I am learning to receive love without suspicion.",
  "I am significant in ways I am only just beginning to understand.",
  "I am worthy of loyalty, time, and devotion.",
  "I carry value into every relationship I touch.",
  "I am creating opportunities through trust and openness.",
  "I am deeply connected to the human story around me.",
  "I bring peace through the way I relate to others.",
  "I am allowed to want closeness and community.",
  "I nurture connection with presence, not perfection.",
  "I am part of something bigger than myself.",
  "I am loved in ways I am still discovering.",
];

// Helper function to get a random daily affirmation
export const getRandomAffirmation = (): string => {
  return dailyAffirmations[Math.floor(Math.random() * dailyAffirmations.length)];
};
